/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "rpcDemo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RpcDemo_PointStamped, RpcDemo_PointStamped, AUTO)


PB_BIND(RpcDemo_PointStamped_Point, RpcDemo_PointStamped_Point, AUTO)


PB_BIND(RpcDemo_PointStamped_Header, RpcDemo_PointStamped_Header, AUTO)


PB_BIND(RpcDemo_Empty, RpcDemo_Empty, AUTO)



