# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63oord.proto\x12\x0cros_messages\"\xd4\x01\n\x0cPointStamped\x12\x31\n\x06header\x18\x01 \x01(\x0b\x32!.ros_messages.PointStamped.Header\x12/\n\x05point\x18\x02 \x01(\x0b\x32 .ros_messages.PointStamped.Point\x1a(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x36\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\r\n\x05stamp\x18\x02 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2L\n\nCoordsComm\x12>\n\tgetCoords\x12\x13.ros_messages.Empty\x1a\x1a.ros_messages.PointStamped\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTSTAMPED._serialized_start=30
  _POINTSTAMPED._serialized_end=242
  _POINTSTAMPED_POINT._serialized_start=146
  _POINTSTAMPED_POINT._serialized_end=186
  _POINTSTAMPED_HEADER._serialized_start=188
  _POINTSTAMPED_HEADER._serialized_end=242
  _EMPTY._serialized_start=244
  _EMPTY._serialized_end=251
  _COORDSCOMM._serialized_start=253
  _COORDSCOMM._serialized_end=329
# @@protoc_insertion_point(module_scope)
